### ISSUE TITLE
backwash pipe

### ISSUE THREAD

**Issue by nwangg** [AguaClara/aide_template#38]

**Comment by nwangg** [comment]
@monroews check if backwash pipe updated correctly

**Comment by monroews** [comment]
Here is a [side view showing the idea](https://github.com/AguaClara/CEE4520/raw/master/Unit_Process_Designs/images/OStaRS_elevations.png) for the siphon pipe route.

**Comment by monroews** [comment]
Do you have an Onshape link for what I am to review? @nwangg

**Comment by nwangg** [comment]
@monroews 
(https://cad.onshape.com/documents/c3a8ce032e33ebe875b9aab4/w/de9ad5474448b34f33fef097/e/138f0ec2c560e210f59dbfb8)

**Comment by monroews** [comment]
I would rotate the invert U part of the pipe 90 degrees so it goes up and back down at the same distance from the filter wall. 

The siphon pipe should include the vertical section of pipe that goes back up and enters the drain channel.
